from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path


FIGSIZE = (6.4, 4.8)
DPI = 300
BLUE = "#1f77b4"
TEAL = "#009E73"
ORANGE = "#E69F00"
GREY = "#8a94a6"
DARK = "#2b2f38"
LIGHT = "#f5f8fb"


def setup_matplotlib():
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update(
        {
            "figure.figsize": FIGSIZE,
            "figure.dpi": DPI,
            "savefig.dpi": DPI,
            "font.family": "serif",
            "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
            "font.size": 10,
            "axes.linewidth": 0.8,
        }
    )
    return plt


def generate_concept_figures(output_dir: str | Path = "06_analysis/paper_figures/concept") -> dict:
    plt = setup_matplotlib()
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    figures = [
        draw_system_model(plt, output / "system_model_isac_uav_swarm.png"),
        draw_protocol_mechanism(plt, output / "protocol_mechanism_itap_nd.png"),
        draw_policy_architecture(plt, output / "policy_architecture_shared_agent.png"),
    ]
    manifest = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "script": str(Path(__file__).resolve()),
        "style": {
            "figsize_inches": list(FIGSIZE),
            "aspect_ratio": "4:3",
            "font_family": "Times New Roman with serif fallback",
            "dpi": DPI,
            "palette": [BLUE, TEAL, ORANGE, GREY, DARK],
        },
        "figures": figures,
    }
    (output / "concept_figure_manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    (output / "README.md").write_text(
        "# Concept Figures\n\n"
        "Reproducible 4:3 paper concept figures generated by `06_analysis/scripts/draw_concept_figures.py`.\n",
        encoding="utf-8",
    )
    return manifest


def draw_system_model(plt, path: Path) -> dict:
    from matplotlib.patches import Circle, FancyArrowPatch, Polygon, Wedge
    import numpy as np

    fig, ax = plt.subplots(figsize=FIGSIZE)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")
    ax.set_title("Self-localized UAV swarm with unknown neighbors", pad=8)

    positions = np.array(
        [
            [0.16, 0.68],
            [0.35, 0.82],
            [0.58, 0.65],
            [0.75, 0.82],
            [0.28, 0.37],
            [0.53, 0.28],
            [0.82, 0.42],
        ]
    )
    occupied_pair = (2, 5)
    for i, j in [(0, 1), (1, 2), (2, 3), (4, 5), (5, 6), (1, 5)]:
        ax.plot([positions[i, 0], positions[j, 0]], [positions[i, 1], positions[j, 1]], "--", color="#b7c2d0", lw=0.9)
    for idx, (x, y) in enumerate(positions):
        draw_uav(ax, x, y, scale=0.025)
        ax.text(x, y - 0.055, f"UAV {idx+1}", ha="center", va="top", fontsize=8, color=DARK)
        color = ORANGE if idx in occupied_pair else BLUE
        wedge = Wedge((x, y), 0.18, 300 if idx % 2 else 25, 345 if idx % 2 else 70, facecolor=color, alpha=0.13, edgecolor=color, lw=1.0)
        ax.add_patch(wedge)
    ax.add_patch(Circle((0.52, 0.55), 0.43, fill=False, ls=":", lw=1.0, ec=GREY))
    ax.add_patch(Circle((0.52, 0.55), 0.31, fill=False, ls="-.", lw=0.9, ec="#9db4c7"))
    ax.text(0.06, 0.08, "Own pose known", color=DARK, fontsize=9)
    ax.text(0.06, 0.035, "Neighbor state unknown before handshake", color=DARK, fontsize=9)
    ax.add_patch(FancyArrowPatch((0.58, 0.62), (0.53, 0.34), arrowstyle="<->", mutation_scale=12, lw=1.3, color=ORANGE))
    ax.text(0.60, 0.49, "candidate beam", color=ORANGE, fontsize=9, rotation=80)
    add_range_legend(ax)
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)
    return generated(path, "system_model")


def draw_protocol_mechanism(plt, path: Path) -> dict:
    from matplotlib.patches import FancyArrowPatch, Rectangle

    fig, ax = plt.subplots(figsize=FIGSIZE)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")
    ax.set_title("ISAC-prior guided link-layer discovery mechanism", pad=8)

    stages = [
        (0.10, "Blind narrow-beam\nhandshake attempt"),
        (0.34, "ISAC occupancy\nbelief update"),
        (0.58, "Candidate beam\nrefinement"),
        (0.82, "Bidirectional\nhandshake confirm"),
    ]
    for x, label in stages:
        ax.add_patch(Rectangle((x - 0.09, 0.57), 0.18, 0.22, fc=LIGHT, ec=BLUE, lw=1.2))
        ax.text(x, 0.68, label, ha="center", va="center", fontsize=9)
    for left, right in zip(stages, stages[1:]):
        ax.add_patch(FancyArrowPatch((left[0] + 0.10, 0.68), (right[0] - 0.10, 0.68), arrowstyle="-|>", mutation_scale=14, color=DARK, lw=1.2))

    draw_beam_grid(ax, 0.08, 0.38, active=[2], empty=[0, 1, 4, 5])
    draw_beam_grid(ax, 0.32, 0.38, active=[2, 6], empty=[0, 1, 3, 4, 5, 7])
    draw_beam_grid(ax, 0.56, 0.38, active=[2, 6], empty=[0, 1])
    draw_beam_grid(ax, 0.80, 0.38, active=[6], empty=[])
    ax.text(0.08, 0.28, "random first probe", ha="center", fontsize=8, color=GREY)
    ax.text(0.32, 0.28, "empty cells suppressed", ha="center", fontsize=8, color=GREY)
    ax.text(0.56, 0.28, "belief + exploration", ha="center", fontsize=8, color=GREY)
    ax.text(0.80, 0.28, "edge added only here", ha="center", fontsize=8, color=GREY)

    ax.add_patch(Rectangle((0.12, 0.10), 0.76, 0.10, fc="#fff8ec", ec=ORANGE, lw=1.0))
    ax.text(
        0.50,
        0.15,
        "ISAC changes beam-selection probabilities; it never creates a neighbor edge without handshake.",
        ha="center",
        va="center",
        fontsize=9,
        color=DARK,
    )
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)
    return generated(path, "protocol_mechanism")


def draw_policy_architecture(plt, path: Path) -> dict:
    from matplotlib.patches import FancyArrowPatch, Rectangle

    fig, ax = plt.subplots(figsize=FIGSIZE)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")
    ax.set_title("Shared local policy for scalable distributed deployment", pad=8)

    block_specs = [
        (0.08, 0.68, 0.20, 0.13, "Self pose\nand beam index", BLUE),
        (0.08, 0.48, 0.20, 0.13, "ISAC belief\nmemory", TEAL),
        (0.08, 0.28, 0.20, 0.13, "Discovered\nneighbor summary", ORANGE),
        (0.40, 0.58, 0.24, 0.18, "Rule residual\nshared policy", DARK),
        (0.72, 0.68, 0.20, 0.13, "Mode choice\nSense/Tx/Rx", BLUE),
        (0.72, 0.48, 0.20, 0.13, "Beam choice\ncandidate set", TEAL),
        (0.72, 0.28, 0.20, 0.13, "Topology-aware\npriority", ORANGE),
    ]
    for x, y, w, h, label, color in block_specs:
        ax.add_patch(Rectangle((x, y), w, h, fc="white", ec=color, lw=1.3))
        ax.text(x + w / 2, y + h / 2, label, ha="center", va="center", fontsize=9, color=DARK)
    for y in (0.745, 0.545, 0.345):
        ax.add_patch(FancyArrowPatch((0.29, y), (0.39, 0.67), arrowstyle="-|>", mutation_scale=12, color=GREY, lw=1.1))
    for y in (0.745, 0.545, 0.345):
        ax.add_patch(FancyArrowPatch((0.65, 0.67), (0.71, y), arrowstyle="-|>", mutation_scale=12, color=GREY, lw=1.1))
    ax.add_patch(Rectangle((0.30, 0.12), 0.40, 0.12, fc=LIGHT, ec=GREY, lw=1.0, ls="--"))
    ax.text(0.50, 0.18, "same parameters reused by every UAV", ha="center", va="center", fontsize=9, color=DARK)
    for x in (0.20, 0.50, 0.80):
        draw_uav(ax, x, 0.90, scale=0.02)
        ax.add_patch(FancyArrowPatch((x, 0.86), (0.50, 0.76), arrowstyle="-", mutation_scale=8, color="#b7c2d0", lw=0.9))
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)
    return generated(path, "policy_architecture")


def draw_uav(ax, x: float, y: float, scale: float = 0.025) -> None:
    from matplotlib.patches import Circle, Rectangle

    ax.add_patch(Rectangle((x - scale, y - scale * 0.45), 2 * scale, scale * 0.9, angle=0, fc=DARK, ec=DARK, lw=0.7))
    for dx, dy in [(-1.6, -1.1), (-1.6, 1.1), (1.6, -1.1), (1.6, 1.1)]:
        ax.plot([x, x + dx * scale], [y, y + dy * scale], color=DARK, lw=0.7)
        ax.add_patch(Circle((x + dx * scale, y + dy * scale), scale * 0.42, fc="white", ec=DARK, lw=0.7))


def draw_beam_grid(ax, x: float, y: float, active: list[int], empty: list[int]) -> None:
    from matplotlib.patches import Rectangle

    cell = 0.027
    for row in range(2):
        for col in range(4):
            idx = row * 4 + col
            color = "white"
            edge = GREY
            alpha = 1.0
            if idx in active:
                color = "#fff2cc"
                edge = ORANGE
            if idx in empty:
                color = "#eef2f6"
                edge = "#c2cad6"
                alpha = 0.6
            ax.add_patch(Rectangle((x + col * cell, y + row * cell), cell * 0.85, cell * 0.85, fc=color, ec=edge, lw=0.8, alpha=alpha))


def add_range_legend(ax) -> None:
    ax.plot([0.72, 0.81], [0.11, 0.11], color="#9db4c7", lw=1.2, ls="-.")
    ax.text(0.83, 0.11, "sensing range", va="center", fontsize=8, color=DARK)
    ax.plot([0.72, 0.81], [0.06, 0.06], color=GREY, lw=1.2, ls=":")
    ax.text(0.83, 0.06, "communication range", va="center", fontsize=8, color=DARK)


def generated(path: Path, role: str) -> dict:
    return {
        "status": "generated",
        "role": role,
        "filename": path.name,
        "path": str(path.resolve()),
        "figsize_inches": list(FIGSIZE),
        "pixel_size": [int(FIGSIZE[0] * DPI), int(FIGSIZE[1] * DPI)],
    }


def main() -> None:
    print(json.dumps(generate_concept_figures(), ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
